
- :user: !ruby/object:Codebreaker::User
    name: User
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 0
  :hints_total: 2
  :hints_used: 0
  :date: 22/07/2022 21:06

- :user: !ruby/object:Codebreaker::User
    name: User
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 0
  :hints_total: 2
  :hints_used: 0
  :date: 22/07/2022 21:10

- :user: !ruby/object:Codebreaker::User
    name: User
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 0
  :hints_total: 2
  :hints_used: 0
  :date: 22/07/2022 21:11

- :user: !ruby/object:Codebreaker::User
    name: User
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 0
  :hints_total: 2
  :hints_used: 0
  :date: 22/07/2022 21:11

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:13

- :user: !ruby/object:Codebreaker::User
    name: '1231'
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 7
  :hints_total: 2
  :hints_used: 2
  :date: 22/07/2022 21:14

- :user: !ruby/object:Codebreaker::User
    name: User
  :difficulty: :easy
  :attempts_total: 15
  :attempts_used: 0
  :hints_total: 2
  :hints_used: 0
  :date: 22/07/2022 21:14
